# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-22 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='status',
            new_name='status_admin',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='status_user',
            field=models.BooleanField(default=False),
        ),
    ]
